# Generated by Django 5.2.5 on 2025-08-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='status',
            new_name='status_pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pagamento',
            field=models.CharField(blank=True, choices=[('Pix', 'Pix'), ('Cartao de Debito', 'Cartão de Débito'), ('Cartao de Credito', 'Cartão de Crédito')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='status_pagamento',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago'), ('Falhou', 'Falhou')], default='Pendente', max_length=20),
        ),
    ]
