# Generated by Django 5.2.5 on 2025-08-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_rename_status_pedido_status_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='imprimir_dois_lados',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documento',
            name='layout',
            field=models.CharField(choices=[('Retrato', 'Retrato'), ('Paisagem', 'Paisagem')], default='Retrato', max_length=10),
        ),
        migrations.AddField(
            model_name='documento',
            name='num_copias',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='documento',
            name='paginas_por_folha',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('4', '4')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo_papel',
            field=models.CharField(max_length=50),
        ),
    ]
