# Generated by Django 5.2.5 on 2025-08-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_documento_imprimir_dois_lados_documento_layout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='taxa_entrega_adicionada',
            field=models.BooleanField(default=False),
        ),
    ]
